### ISSUE TITLE
Initialize position object

### ISSUE THREAD

**Issue by devNoiseConsulting** [fbongiovanni29/opportunities#3]
Initialize position object with a minimum set of attributes. This would help to keep the attributes order the way we've generally populated the positions. 

```
var obj = {
    "@context": "http://schema.org",
    "@type": "JobPosting",
    "employmentType": null,
    "title": null,
    "alternateName": null,
    "url": null,
    "jobLocation": null,
    "remote": null,
    "datePosted": null
};
```

Note: I've include alternateName even though I don't expect the crawler to populate that value.

**Comment by fbongiovanni29** [comment]
Updated code
